In [1]:
import numpy as np
from numpy.typing import NDArray
from pathlib import Path
from pprint import pprint

from tarea2.algorithms import *
from tarea2.io import *
from tarea2.gen import *


# Obtener los datos

In [2]:
# Datos de la ayudantía 11

# OBTENER PARÁMETROS Y VARIABLES
################################

A = np.array([
  [1, -2, 1, 0],
  [-1, 1, 0, 1]
], dtype=np.float64)

b = np.array([
  [4],
  [3]
])

c = np.array([
  [-1],
  [-3],
  [0],
  [0],
])

B = np.array([2, 3])
NB = np.array([0, 1])

X = np.zeros(shape=c.shape)


# COMIENZA ALGORITMO SIMPLEX
############################
# ENTRADAS: A, b, c, B, NB

for i in range(2):
  print("A:")
  pprint(A)

  print("B:")
  pprint(B)

  print("A[B]:")
  pprint(A[:,B])

  print("NB:")
  pprint(NB)

  print("A[NB]:")
  pprint(A[:,NB])


  X[B] = np.dot(np.linalg.inv(A[:,B]), b)
  X[NB] = 0

  print("X:")
  pprint(X)

  print("X[B]:")
  pprint(X[B])

  print("X[NB]:")
  pprint(X[NB])


  # Verificar si es:
  # - básica
  # - factible
  # - no negativa
  # - no degenerada

  if not es_factible(X[B]):
    print("X no factible")
    raise RuntimeError("Se llega a solución no factible")

  if es_optimo(X):
    print("La respuesta es: ")
    print(X)


  # DETERMINAR DIRECCIONES Y COSTOS REDUCIDOS
  ###########################################

  # Lo más sensato es empezar con una solución básica factible
  # Luego derivar la base, no-base y seguir.
  d_cr_list = lista_direccion_costos_reducidos(X, A, c, B, NB)
  print("\nLista de direcciones y costos reducidos: ")
  pprint(d_cr_list)


  # ENCONTRAR DIRECCIÓN Y PASO
  ############################

  print("\nCosto básico solución básica X_B: ")
  pprint(c[B])

  # Determinar dirección con menor costo reducido
  # (NB_i, d, cr)
  d_cr_min = min(d_cr_list, key=lambda x: x[2])

  print("\nDirección de menor costo reducido: ")
  pprint(d_cr_min)

  # Obtener componentes de la dirección de menor costo reducido que:
  # - Pertenezcan a la base.
  # - Sean menores a cero.

  B_menores_a_cero = [B[i] for i, d_i in enumerate( d_cr_min[1][B] ) if d_i < 0]

  print(f"{B_menores_a_cero = }")

  # Obtener la lista de coeficientes de desplazamientos posibles
  phi_list = [(- X[i] / d_cr_min[1][i], i) for i in B_menores_a_cero]

  # Quedarse con el menor, y determinar su índice (El que sale)
  phi, B_sale = min(phi_list)

  print(f"{phi_list = }")
  print(f"{phi = }")


  # ACTUALIZAR BASE Y NO_BASE
  ########################################

  NB_entra = d_cr_min[0]
  B_sale_row =   np.where(B == B_sale)[0][0]
  NB_entra_row = np.where(NB == NB_entra)[0][0]

  print()
  print(f"Entra a la base: {NB_entra}")
  print(f"Sale de la base: {B_sale}")

  B.put(B_sale_row, NB_entra)
  NB.put(NB_entra_row, B_sale)

  print()
  print("B actualizado:")
  pprint(B)
  print("NB actualizado:")
  pprint(NB)

  print()
  print()
  print()
  print()

A:
array([[ 1., -2.,  1.,  0.],
       [-1.,  1.,  0.,  1.]])
B:
array([2, 3])
A[B]:
array([[1., 0.],
       [0., 1.]])
NB:
array([0, 1])
A[NB]:
array([[ 1., -2.],
       [-1.,  1.]])
X:
array([[0.],
       [0.],
       [4.],
       [3.]])
X[B]:
array([[4.],
       [3.]])
X[NB]:
array([[0.],
       [0.]])
Tenemos un óptimo
Son múltiples óptimos
La respuesta es: 
[[0.]
 [0.]
 [4.]
 [3.]]

Lista de direcciones y costos reducidos: 
[(0, array([[ 1.],
       [ 0.],
       [-1.],
       [ 1.]]), -1.0),
 (1, array([[ 0.],
       [ 1.],
       [ 2.],
       [-1.]]), -3.0)]

Costo básico solución básica X_B: 
array([[0],
       [0]])

Dirección de menor costo reducido: 
(1, array([[ 0.],
       [ 1.],
       [ 2.],
       [-1.]]), -3.0)
B_menores_a_cero = [3]
phi_list = [(array([3.]), 3)]
phi = array([3.])

Entra a la base: 1
Sale de la base: 3

B actualizado:
array([2, 1])
NB actualizado:
array([0, 3])




A:
array([[ 1., -2.,  1.,  0.],
       [-1.,  1.,  0.,  1.]])
B:
array([2, 1])
A[B]:
ar

ValueError: min() arg is an empty sequence