In [1]:
import pandas as pd
from pathlib import Path
import numpy as np

def data(data_path: Path):
  alpha_i_path = data_path / "alpha_i.csv"
  if alpha_i_path.exists():
    print("El archivo alpha_i.csv existe :)")

  beta_j_path = data_path / "beta_j.csv"
  if beta_j_path.exists():
    print("El archivo beta_j.csv existe :)")

  a_ij_path = data_path / "a_ij.csv"
  if a_ij_path.exists():
    print("El archivo a_ij.csv existe :)")


  alpha_i = pd.read_csv(alpha_i_path, header=None).to_numpy() # Oferta de nodo origen
  beta_j = pd.read_csv(beta_j_path, header=None).to_numpy()   # Demanda de nodo destino
  a_ij = pd.read_csv(a_ij_path, header=None).to_numpy()

  return alpha_i, beta_j, a_ij

def gen_A(I: list, J: list):

  I_N = len(I)
  J_N = len(J)

  # Mapea entre una restricción X_ij a un índice de la matriz A.
  IJ = np.arange(I_N*J_N).reshape(I_N, J_N)

  A = np.zeros(shape=(I_N + J_N, I_N * J_N))

  # Cada fila de la matriz A representa una restricción de igualdad.
  restriccion_base = 0

  # Por cada nodo fuente i
  # la suma de demanda de cada destino debe igualar a su oferta
  for i in I:
    for j in J:
      A[restriccion_base][IJ[i, j]] = 1

    restriccion_base += 1

  # Por cada nodo destino j
  # Su demanda debe ser satisfecha por todos los nodos
  for j in J:
    for i in I:
      A[restriccion_base][IJ[i, j]] = 1

    restriccion_base += 1

  return A

def gen_b(oferta_i, demanda_j):
  return np.append(oferta_i,  demanda_j)

# Tarea 2

## Conjuntos

$I$: Conjunto de nodos origen. En los datos reales son 20.

$J$: Conjunto de nodos destino. En los datos reales son 30.

## Parámetros

$\alpha_i$: Oferta del nodo origen. Originalmente son 20 datos.

$\beta_i$: Demanda del nodo destino. Originalmente son 30 datos.

$a_{i,j}$: Costo de transporte unitario del nodo origen "i" a nodo destino "j".

In [2]:
oferta_i, demanda_j, costo_ij = data(Path("data_reduced"))

I_N = len(oferta_i)
J_N = len(demanda_j)

I = [i for i in range(I_N)] # N=20, Conjunto de origenes, quienes ofrecen
J = [j for j in range(J_N)]  # M=30, Conjunto de destinos, quienes demandan


IJ = np.arange(I_N*J_N).reshape(I_N, J_N)
# Esta variable permite recorrer las columnas según una base.
# la base especifica la restricción.

# El gran problema de este ejercicio es que tenemos que transformar las dos
# dimensiones, oferta y demanda, en una sola para poder operar con simplex.

# Posiblemnete se puede operar de forma multidimensional, en este trabajo
# se opera de manera bidimensional, aplanando las coordenadas [i, j]

print(IJ)

for i in I:
  for j in J:
    print(IJ[i, j])

El archivo alpha_i.csv existe :)
El archivo beta_j.csv existe :)
El archivo a_ij.csv existe :)
[[0 1 2]
 [3 4 5]]
0
1
2
3
4
5


In [4]:
A = gen_A(I, J)
b = gen_b(oferta_i, demanda_j)

print(A)
print(b)

[[1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1.]
 [1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]]
[3656 3661 3306 1359 2792]
