In [1]:
import numpy as np
from pathlib import Path

from tarea2.algorithms import simplex_normalization, north_west_heuristic
from tarea2.io import get_data
from tarea2.gen import gen_A , gen_b, gen_mapping

In [8]:
#data_path = Path("data")
data_path = Path("data_reduced")
#data_path = Path("northwest_example")
I, J, oferta_i, demanda_j, costos_ij = get_data(data_path)


A = gen_A(I, J)
b = gen_b(oferta_i, demanda_j)
mapping = gen_mapping(I, J)

El archivo alpha_i.csv existe :)
El archivo beta_j.csv existe :)
El archivo a_ij.csv existe :)


In [9]:
solucion_1 = north_west_heuristic(oferta_i, demanda_j, costos_ij)

   oferta_actual = 3656
   demanda_actual = 3306
   - demanda_actual es menor
[[ 350]
 [3661]]
[[   0]
 [1359]
 [2652]]

   oferta_actual = 350
   demanda_actual = 1359
   - oferta_actual es menor
[[   0]
 [3661]]
[[   0]
 [1009]
 [2652]]

   oferta_actual = 3661
   demanda_actual = 1009
   - demanda_actual es menor
[[   0]
 [2652]]
[[   0]
 [   0]
 [2652]]

   oferta_actual = 2652
   demanda_actual = 2652
   - iguales
Se llega al equilibrio


In [10]:
(solucion_1* costos_ij).sum()

2770573.0

In [11]:
costos_ij

array([[603, 272, 527],
       [886, 363, 119]], dtype=int64)